openapi: "3.0.1"
info:
  title: Backend API ${api_name}
  version: "1.0"
paths:
  /get_presigned_url:
    get:
      responses:
        "200":
          description: "200 response"
          content: {}
      security:
      - CognitoAuthorizer:
        - "Blogger"
        - "Admin"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        credentials: ${apigateway_role_arn}
        httpMethod: "POST"
        uri: ${lambda_invoke_arn}
        requestTemplates:
          application/json: "{\"body\": \"$input.json(\\\"$\\\" )\"}"
        passthroughBehavior: "when_no_match"
  /:
    get:
      responses:
        "200":
          description: "200 response"
          content: {}
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        credentials: ${apigateway_role_arn}
        httpMethod: "POST"
        uri: ${lambda_invoke_arn}
        requestTemplates:
          application/json: "{\"body\": \"$input.json(\\\"$\\\" )\"}"
        passthroughBehavior: "when_no_match"
components:
  securitySchemes:
    CognitoAuthorizer:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"
      x-amazon-apigateway-authorizer:
        type: "cognito_user_pools"
        providerARNs:
        - "arn:aws:cognito-idp:us-east-1:120306595012:userpool/us-east-1_H6EVy7Q3H"
