openapi: 3.0.0
info:
  title: Backend API ${api_name}
  version: 1.0
paths:
  /:
    get:
      summary: Get Lambda response
      responses:
        '200':
          description: Successful response
      x-amazon-apigateway-integration: # Integration configuration within the spec
        credentials: ${apigateway_role_arn}
        uri: ${lambda_invoke_arn}
        passthroughBehavior: when_no_match
        httpMethod: post
        type: aws_proxy
        requestParameters: {}
        requestTemplates:
          application/json: '{"body": "$input.json(\"$\" )"}'
      x-amazon-apigateway-method-response: # Method response within the spec
        statusCode: "200"
        responseParameters: {}
        responseModels: {}