# Use a Node.js base image for building the app
FROM node:20 as build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if it exists)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app's code
COPY . .

# Build the React app for production
RUN npm run build

# Use a smaller Nginx image to serve the static files
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the build output from the build stage to Nginx's HTML directory
COPY --from=build /app/build /usr/share/nginx/html

ENV NODE_ENV production

# Expose port 80 (the default port Nginx listens on)
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]